[package]

name = "current"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>"
]
tags = []

[lib]

name = "current"
path = "src/lib.rs"

[dependencies.modifier]

git = "https://github.com/reem/rust-modifier"

